### ISSUE TITLE
bug: missing dependency in package.json

### ISSUE THREAD

**Issue by takanome-dev** [0-vortex/nestjs-test-tooling#1]
Hey @0-vortex, thanks for putting together this great template ❤️ 

Just used it to spin a new project and while starting the server, I noticed that `class-validator` is missing in the deps.

<img width="833" alt="SCR-20240219-ssdq" src="https://github.com/0-vortex/nestjs-test-tooling/assets/79809121/c53fdd88-e9e4-4611-a84d-40e99287bee3">
 
Would be more than happy to send a pr if welcomed :)

**Comment by 0-vortex** [comment]
Thanks a lot, I have since moved to experimenting with a real world scenario: https://github.com/TMCB-SPACE/nestjs-realworld-price-collector-app

Let me know if you find that boilerplate more enticing 🔥 🚀

**Comment by takanome-dev** [comment]
> Let me know if you find that boilerplate more enticing 

It's great, I love it 😁 Just need to set up redis and clickhouse 👍

**Comment by 0-vortex** [comment]
Or remove them :D
